menu:
    Blog: /
    About: /about-me/
    # Twitter: https://twitter.com/ryanral_ph
    Linkedin: https://www.linkedin.com/in/rralph/
    # GitHub: https://github.com/ryanralph
    HarnessLogic: https://harnesslogic.com
    # Keybase: https://keybase.io/ryanralph
    Archive: /archives/
    Contact: mailto:blog@ryanralph.com
    # Rss: /atom.xml

language: en

favicon: favicon.ico
logo: //www.gravatar.com/avatar/79178899751f1701e50ad5ac9ff386c4?s=200

# Comment
# e.g disqus: seansun
# disqus: ryanralph
# duoshuo:

# Analytics
google-analytics:
ga: G-R5BM2X0K10

# Copyright Infomation
startyear: 2013
