menu:
    Blog: /
    Twitter: https://twitter.com/ryanral_ph
    GitHub: https://github.com/ryanralph
    Keybase: https://keybase.io/ryanralph
    Archive: /archives/
    # Rss: /atom.xml

language: en

favicon: favicon.ico
logo: //www.gravatar.com/avatar/79178899751f1701e50ad5ac9ff386c4?s=200

# Comment
# e.g disqus: seansun
disqus: ryanralph
# duoshuo:

# Analytics
google-analytics:
ga: UA-61359637-1

# Copyright Infomation
startyear: 2013
